### ISSUE TITLE
no child elements

### ISSUE THREAD

**Issue by HarriAlasi** [Ashp116/node-xml-to-json#1]
I am trying to parse a sepa payment from an example xml.

Consider the following file

    <GrpHdr>
      <MsgId>Message-ID-4711</MsgId>
      <CreDtTm>2010-11-11T09:30:47.000Z</CreDtTm>
      <NbOfTxs>2</NbOfTxs>
      <InitgPty>
        <Nm>Initiator Name</Nm>
      </InitgPty>
    </GrpHdr>

(I have stripped most of the xml for length sake)
And trying to get the json string with

     this.httpClient.get('../../../assets/xsd/exampleSepaPayment.xml', {responseType: 'text'}).
          subscribe(xsd => {
            const x = toJSON(xsd, {beautify: true});
            console.log(x);
            },
          );

howewer, the console shows

     {
    
	      "GrpHdr": {}
      }

Child elements don't seem to get parsed at all

**Comment by Ashp116** [comment]
Hi there! so I tested the XML data and it parsed it to JSON. can you show me what `xsd` prints as?

**Comment by Ashp116** [comment]
I just updated the lib, redownload the lib.

**Comment by HarriAlasi** [comment]
Looks like the file import from has some newline identifiers that do not work well. or it has something to do with my ...encoding?
I tried with inputting my example string directly and this worked

```
const x = toJSON("<GrpHdr><MsgId>Message-ID-4711</MsgId><CreDtTm>2010-11-11T09:30:47.000Z</CreDtTm> 
   <NbOfTxs>2</NbOfTxs><InitgPty><Nm>Initiator Name</Nm></InitgPty></GrpHdr>", {beautify: true});

```
All on one line.

**But this didn't**

```
        const x = toJSON('<GrpHdr>\n' +
          '  <MsgId>Message-ID-4711</MsgId>\n' +
          '  <CreDtTm>2010-11-11T09:30:47.000Z</CreDtTm>\n' +
          '  <NbOfTxs>2</NbOfTxs>\n' +
          '  <InitgPty>\n' +
          '    <Nm>Initiator Name</Nm>\n' +
          '  </InitgPty>\n' +
          '</GrpHdr>', {beautify: true});
```
I copied/pasted the code block from here directly,

**Comment by HarriAlasi** [comment]
I don't know how did I close this!?

**Comment by Ashp116** [comment]
Hi there, so I am confused, did you fix the problem?

**Comment by HarriAlasi** [comment]
Hi. I closed It by accident.
To recap - if all content is on one line, it seems to work

**Comment by Ashp116** [comment]
I just updated the lib, it was a bug. My function couldn't parse the `\n` with multiple lines. I just fixed that error it should work now. Can you test it out?
